/**
 * Build-time generated virtual module type declarations.
 *
 * Note: this file must stay a "global script" (no top-level import/export),
 * otherwise `declare module` is treated as module augmentation and requires
 * the original module to already exist. So types use inline `import type`.
 */
declare module 'virtual:docs-index' {
  import type { DocMeta } from '../lib/docs/types'

  /** Generated by build/docsIndexPlugin.ts from src/content md files (meta only, no body) */
  const docsIndex: DocMeta[]
  export default docsIndex
  export { docsIndex }
}

declare module 'virtual:travel-index' {
  import type { TripMeta } from '../lib/travel/types'

  /** Generated by build/travelIndexPlugin.ts from src/content/travel/*.json */
  const travelIndex: TripMeta[]
  export default travelIndex
  export { travelIndex }
}